### ISSUE TITLE
1.5.0 changes default load order of migrations

### ISSUE THREAD

**Issue by jrh-exacta** [mycodeself/mongo-migrate-ts#113]
Upgrading to 1.5.0 changes the default load behavior of the migrations, my migrations are set up as so.

```/jrh-exacta/dev/super-app/
    └── build/
        └── mongo/
            └── migrations/
                ├── 1713446102472_create_clientTelemetry.js
                ├── 1713804829014_AddClientTelemetryLevelIndex.js
                ├── 1714121370285_add_percentage_to_pools.js
                ...
```
with 1.4.0 the migrations are loaded in ```1713446102472_create_clientTelemetry.js->17113804829014_AddClientTelemetryLevelIndex.js->1714121370285_add_percentage_to_pools.js```

now with 1.5.0 the migrations loaded in ```1714121370285_add_percentage_to_pools.js->1713804829014_AddClientTelemetryLevelIndex.js->1713446102472_create_clientTelemetry.js```

This breaks any migration set up I have had in the past.  I could not see a way to make the glob options reverse the order?  Is that possible?

**Comment by mycodeself** [comment]
Hey, this should be fixed in 1.6.2, could you try and let me know if the problem persists?

Thanks!
