### ISSUE TITLE
No migrations found when running in ts-node 

### ISSUE THREAD

**Issue by Dalfons0** [mycodeself/mongo-migrate-ts#17]
Using the version 1.0.9 doesn't detect properly when running in ts-node.
I tried to make a migration using the following commands:
```
$ env-cmd tsnd src/migrations/index.ts up
$ ts-node-dev -r dotenv/config src/migrations/index.ts up
$ ts-node -r dotenv/config src/migrations/index.ts up
```
And despite them executes the index with ts-node (direct or indirectly), the function [isTsNode](https://github.com/mycodeself/mongo-migrate-ts/blob/master/lib/utils/isTsNode.ts) doesn't return true making the [loadMigrations](https://github.com/mycodeself/mongo-migrate-ts/blob/master/lib/migrations.ts#L44) function looking for files with js extensions, so the command ends without finding any migrations:
![image](https://user-images.githubusercontent.com/24602242/80007831-1d1cb380-84c7-11ea-83e8-7ee6b373efa0.png)

I solved this downgrading to the version 1.0.6, but I think it's something to take in consideration in future versions.

**Comment by mycodeself** [comment]
Hi,

i have tested it and it works.

Make sure you have the latest version of the library and the correct configuration.

```
yarn ts-node src/migrations/index.ts up
yarn run v1.22.4
warning package.json: No license field
$ ts-node src/migrations/index.ts up
✔ Migration MyMigration up
✔ 1 migrations up
Done in 1.16s.
```
Environment:
```
"mongo-migrate-ts": "^1.0.9",
"ts-node": "^8.9.0",
"ts-node-dev": "^1.0.0-pre.44",
"typescript": "^3.8.3"
```

I strongly recommend using the latest version,

regards
