### ISSUE TITLE
Migration naming

### ISSUE THREAD

**Issue by amirqasemi74** [mycodeself/mongo-migrate-ts#29]
I think it is better to accept a name for creating new migration

**Comment by mycodeself** [comment]
Hi, thanks for your suggestion!

You should be able to do this with the -n parameter when running the new command

`'-n, --name <name>', 'the migration name'`

let me know if you have any issue

**Comment by amirqasemi74** [comment]
So I think with a better documentation you can achieve more download.
tanx
