### ISSUE TITLE
Run up and down programatically?

### ISSUE THREAD

**Issue by kelvin-thinkbean** [mycodeself/mongo-migrate-ts#56]
[migrate-mongo](https://github.com/seppevs/migrate-mongo) exports and [API](https://github.com/seppevs/migrate-mongo#api-usage) that you can use to run the commands programatically.

I don't see this available in this library but I am not sure if it is hidden somewhere. Please let me know.

**Comment by scottsandersdev** [comment]
I was able to import the commands manually through the dist folder 
```
import { up } from "mongo-migrate-ts/dist/lib/commands/up";
```
