### ISSUE TITLE
Error: Cannot find module 'mongodb'

### ISSUE THREAD

**Issue by maulikpatel-in** [mycodeself/mongo-migrate-ts#57]
<img width="1437" alt="Screenshot 1943-12-11 at 11 46 01 PM" src="https://user-images.githubusercontent.com/13593466/156423209-fcb092a7-3e2f-4dd5-9f17-3dcc81f2b5d8.png">

What Step I have perform: 

`npm install -g mongo-migrate-ts`

and Inside project directory:
`mongo-migrate init`

**Comment by Krispy2009** [comment]
If I manually run `npm install mongodb` in the mongo-migrate-ts folder it works, so it seems to me that we need to open a PR to add that dependency to the mongo-migrate-ts library. 

@mycodeself thoughts? I can open the PR if that's the way to go.

**Comment by mycodeself** [comment]
yes @Krispy2009 you're right, I think I removed it from the `devDependencies` by mistake during upgrading major versions of dependencies. 

Feel free to open a PR or I'll try to solve it when I've some time!

**Comment by Krispy2009** [comment]
@mycodeself It looks like it's still there in the `peerDependencies` so no PR needed.

I've tried installing it and I can see a warning that I have to install peer dependencies myself. When I do  (e.g `npm install -g mongodb`) the issue goes away. 

From the node docs:
```
UPDATE: npm versions 1, 2, and 7 will automatically install peerDependencies if they are not 
explicitly depended upon higher in the dependency tree. 
For npm versions 3 through 6, you will receive a warning that the peerDependency is not installed instead.
```
☝️ npm v8 also installs peer dependencies automatically.

So, @maulikpatel-in it looks like you are using a version of npm that does not install peer dependencies automatically. Please try to install mongodb (`npm install -g mongodb`) and try running `mongo-migrate init` again.

**Comment by mycodeself** [comment]
@Krispy2009 right, thank you very much for your time reviewing this.

since there is no issue, I close this. 

@maulikpatel-in  feel free to open a new issue if you encounter any problems.
