### ISSUE TITLE
Use .env variable to set a DB URI

### ISSUE THREAD

**Issue by arcenojackson** [mycodeself/mongo-migrate-ts#60]
Is it possible to use an environment variable to set the connection URI with mongo?

**Comment by arcenojackson** [comment]
sorry, I looked through old issues and found that what I wanted

**Comment by Hassan829** [comment]
Please share the link

**Comment by arcenojackson** [comment]
Hey, here is the link: https://github.com/mycodeself/mongo-migrate-ts/issues/17

But basically, you need to use the "-r" flag with "dotenv/config"

**Comment by Hassan829** [comment]
then there is no need to define db string in .json file?

**Comment by arcenojackson** [comment]
> 

No, you not need it.
You just need define the db string in .env file and refer it on mongo-migrate .ts/.js file, using process.env.DB_STRING

**Comment by danishm7012** [comment]
Error: Invalid configuration, uri is empty. I got this

**Comment by arcenojackson** [comment]
> Error: Invalid configuration, uri is empty. I got this

@danishm7012 Have you set the db string in .env and configure the migrate.config.ts?

Here is how I do:
- package.json's scripts
```
"migrate:new": "ts-node migrate.config.ts new -t ./migrations/template/new-migration.ts -n",
"migrate:up": "ts-node -r dotenv/config migrate.config.ts up",
"migrate:status": "ts-node -r dotenv/config migrate.config.ts status",
"migrate:down": "ts-node -r dotenv/config migrate.config.ts down -l",
```

- .env
`MONGODB_URI=mongodb://admin:admin@mongo:27017/database?authSource=admin`

- migrate.config.ts
```
import { mongoMigrateCli } from 'mongo-migrate-ts';

mongoMigrateCli({
  uri: process.env.MONGODB_URI || '',
  database: '',
  migrationsDir: './migrations',
  migrationsCollection: 'changeCollections',
  options: {},
});
```

**Comment by mikeantonelli** [comment]
Small update to @arcenojackson's example - I was able to resolve by adding dotenv in migrate.config.ts:

```ts
import * as dotenv from 'dotenv';
import { mongoMigrateCli } from 'mongo-migrate-ts';
import path from 'path';

// Load environment variables from .env file
dotenv.config({ path: path.join(__dirname, '.env') });

mongoMigrateCli({
  uri: process.env.DB_CONN_STRING || '',
  database: '',
  migrationsDir: './migrations',
  migrationsCollection: 'changeCollections',
  options: {}
});
```
