### ISSUE TITLE
Sample migration file

### ISSUE THREAD

**Issue by vgandzyuck** [mycodeself/mongo-migrate-ts#61]
Overriding the sample migration

To override the content of the sample migration that will be created by the create command, create a file sample-migration.js in the migrations directory.

Is it possible to make something similar, to avoid linter erorrs and e.t.c?

**Comment by mycodeself** [comment]
Hi, if I understand correctly you are referring to something that has been implemented in version 1.1.0 in this PR https://github.com/mycodeself/mongo-migrate-ts/pull/59 

This is what you mean, isn't it?
