### ISSUE TITLE
Error executing migrations

### ISSUE THREAD

**Issue by mezdon** [mycodeself/mongo-migrate-ts#66]
When I use the `ts-node migrations/index.ts up` command to execute migrations I get the following error 

`Error executing migration Migration1658840191491
✖ Error executing migrations
ExecuteMigrationError: MongoServerError: ns not found`

The command only executes the first migration and all others throw an error.

my index.ts file contains the following:

`import { mongoMigrateCli } from "mongo-migrate-ts";
import 'dotenv/config';

mongoMigrateCli({
	uri: `mongodb:${process.env.MONGO_HOST}`,
	database: `${process.env.MONGO_DB}`,
	migrationsDir: __dirname,
	migrationsCollection: "migrations_collection",
});`

**Comment by mycodeself** [comment]
I think this error occurs when a collection doesn't exists, did you solve it? feel free to open this again with more information if the problem persists
