### ISSUE TITLE
Transactions support

### ISSUE THREAD

**Issue by art049** [mycodeself/mongo-migrate-ts#68]
Hey, thanks a lot for this package!

I think it would be really nice to be able to enable transactions (when the instance supports it) to wrap up the migration execution.

I'd be thrilled to implement this if you support this :)

**Comment by mycodeself** [comment]
would be nice if you can make a PR

**Comment by jacknewberry** [comment]
`migrate-mongo` enables this by providing a MongoClient to the migration handlers:
https://github.com/seppevs/migrate-mongo#using-mongodbs-transactions-api

Passing in a Session might work too.

**Comment by mycodeself** [comment]
Hey @art049 and @jacknewberry 

I have added support for transactions, any feedback is welcome!

See https://github.com/mycodeself/mongo-migrate-ts#transactions
