### ISSUE TITLE
Down Function does not seem to work

### ISSUE THREAD

**Issue by vijayrzr** [mycodeself/mongo-migrate-ts#69]
When I call the down function, for some reason, it does not work and in terminal I see output as if you had called for a --help command. Any idea why the down function is not working or how to debug this?

![image](https://user-images.githubusercontent.com/52078472/196766887-9af01503-bc5c-4f60-a4f8-f3728bd8673a.png)

**Comment by gabkk** [comment]
Use -l for last 
```
    program
      .command('down')
      .description('Undo migrations')
      .option('-l, --last', 'Undo the last applied migration')
      .option('-a, --all', 'Undo all applied migrations')
      .action((opts) => {
        if (!opts.last && !opts.all) {
          program.outputHelp();
          process.exit(-1);
        }

        down({
          config,
          mode: opts.last ? 'last' : 'all',
        });
      });
```
