### ISSUE TITLE
add glob option to pick migrations

### ISSUE THREAD

**Issue by y-nk** [mycodeself/mongo-migrate-ts#72]
mostly if somebody is ever interested into _testing_ their migrations before, the obvious choice will be to do:

```
/migrations
  1234567890-migration.ts
  1234567890-migration.test.ts
```

then when you do `index up` then the `.test` runs as a migration. bummer

**Comment by y-nk** [comment]
😓

**Comment by mycodeself** [comment]
Hi @y-nk although a little late :D

I see this as something interesting to implement if anyone is up for it

**Comment by y-nk** [comment]
made a PR, maybe too late 🤷
