### ISSUE TITLE
Can't be used from CI/CD platform (always returns a zero exit code)

### ISSUE THREAD

**Issue by m0un10** [mycodeself/mongo-migrate-ts#74]
This tool can't be used with a CI/CD platform because if an exception happens it exits with 0. This means that no one will be able to detect that an issue has happened. The pipeline will simply imply everything is ok.

**Comment by mycodeself** [comment]
Hi I have applied a fix in this PR #80 please try using latest version https://github.com/mycodeself/mongo-migrate-ts/releases/tag/v1.1.3 and let me know if the problem persists!
