### ISSUE TITLE
MongoDB version constraint

### ISSUE THREAD

**Issue by dylankerr-bis** [mycodeself/mongo-migrate-ts#86]
The `mongodb` package is listed in the peerDependencies at major version 4, which is preventing me from updating `mongodb` to the latest major version.
Is there any compatibility issues with version 5 that require version 4 specifically? My testing so far shows that version 5 works fine, but it's possible I haven't tested everything.
In any case, thank you for sharing this package, it is very useful.

**Comment by gustawdaniel** [comment]
yes, it is compatible with mongo v5

**Comment by mycodeself** [comment]
Closed by #91 

Thanks a lot @gustawdaniel !
